# 2016.5.25调试日志

```shell
Xshell 5 (Build 0446)
Copyright (c) 2002-2014 NetSarang Computer, Inc. All rights reserved.

Type `help' to learn how to use Xshell prompt.
[C:\Users\kangcunhua]$ 

Connecting to 127.0.0.1:2222...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

Last login: Thu May 26 15:18:15 2016 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
[vagrant@OpsDev2 ~]$ df -k
Filesystem           1K-blocks    Used Available Use% Mounted on
/dev/mapper/VolGroup-lv_root
                       8561112 1554912   6564652  20% /
tmpfs                   510144       0    510144   0% /dev/shm
/dev/sda1               487652   27666    434386   6% /boot
vagrant               52436988 5485900  46951088  11% /vagrant
vagrant_data          52436988 5485900  46951088  11% /vagrant_data
PythonHome_wwwroot    52436988 5485900  46951088  11% /PythonHome/wwwroot
[vagrant@OpsDev2 ~]$ cd /PythonHome/wwwroot/Lesson01
[vagrant@OpsDev2 Lesson01]$ ls
document  jsonrpc.py  modules  readme.md  tt.py
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
  File "jsonrpc.py", line 31
    102: "模块加载失败"
      ^
SyntaxError: invalid syntax
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
  File "jsonrpc.py", line 267
    def __init__(self，testflag):
                     ^
SyntaxError: invalid syntax
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
测试getIdc()方法
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
Traceback (most recent call last):
  File "jsonrpc.py", line 330, in <module>
    requestTmp = Request()
TypeError: __init__() takes exactly 2 arguments (1 given)
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
AttributeError: 'JsonRPC' object has no attribute 'validata_all'
[vagrant@OpsDev2 Lesson01]$ ^C
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
  File "jsonrpc.py", line 132, in validata_all
    for func in [self.validate_mandatory, validata_id, self.validata_HasModule, self.validata_hasFunction]:
NameError: global name 'validata_id' is not defined
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
id:1
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
  File "jsonrpc.py", line 133, in validata_all
    if not func():
  File "jsonrpc.py", line 115, in validata_HasModule
    self.response_preform.printlogs("导入模块报错：" + e)
TypeError: cannot concatenate 'str' and 'exceptions.AttributeError' objects
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
id:1
[2016-05-27 03:22:01]导入模块报错：'NoneType' object has no attribute 'setAndReturnModule'
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
  File "jsonrpc.py", line 133, in validata_all
    if not func():
TypeError: validata_hasFunction() takes no arguments (1 given)
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
id:1
[2016-05-27 03:22:48]导入模块报错：'NoneType' object has no attribute 'setAndReturnModule'
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
  File "jsonrpc.py", line 133, in validata_all
    if not func():
  File "jsonrpc.py", line 119, in validata_hasFunction
    if (not self.module) and hasattr(self.module, self.funcname):
AttributeError: 'JsonRPC' object has no attribute 'funcname'
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
id:1
[2016-05-27 03:24:52]导入模块报错：'NoneType' object has no attribute 'setAndReturnModule'
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
  File "jsonrpc.py", line 133, in validata_all
    if not func():
  File "jsonrpc.py", line 122, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module + "没有此函数" + self.funcname)
TypeError: cannot concatenate 'str' and 'NoneType' objects
[vagrant@OpsDev2 Lesson01]$ ntpdate
-bash: ntpdate: command not found
[vagrant@OpsDev2 Lesson01]$ yum install ntp
Loaded plugins: fastestmirror
You need to be root to perform this command.
[vagrant@OpsDev2 Lesson01]$ sudo su -
[root@OpsDev2 ~]# yum install ntp
Loaded plugins: fastestmirror
Setting up Install Process
Determining fastest mirrors
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
base                                                                     | 3.7 kB     00:00     
base/primary_db                                                          | 4.7 MB     00:47     
extras                                                                   | 3.4 kB     00:00     
extras/primary_db                                                        |  36 kB     00:03     
updates                                                                  | 3.4 kB     00:00     
updates/primary_db                                                       |  89 kB     00:02     
Resolving Dependencies
--> Running transaction check
---> Package ntp.x86_64 0:4.2.6p5-10.el6.centos will be installed
--> Processing Dependency: ntpdate = 4.2.6p5-10.el6.centos for package: ntp-4.2.6p5-10.el6.centos.x86_64
--> Running transaction check
---> Package ntpdate.x86_64 0:4.2.6p5-10.el6.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================
 Package            Arch              Version                             Repository       Size
================================================================================================
Installing:
 ntp                x86_64            4.2.6p5-10.el6.centos               base            598 k
Installing for dependencies:
 ntpdate            x86_64            4.2.6p5-10.el6.centos               base             78 k

Transaction Summary
================================================================================================
Install       2 Package(s)

Total download size: 676 k
Installed size: 1.8 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): ntp-4.2.6p5-10.el6.centos.x86_64.rpm                              | 598 kB     00:04     
(2/2): ntpdate-4.2.6p5-10.el6.centos.x86_64.rpm                          |  78 kB     00:00     
------------------------------------------------------------------------------------------------
Total                                                           122 kB/s | 676 kB     00:05     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : ntpdate-4.2.6p5-10.el6.centos.x86_64                                         1/2 
  Installing : ntp-4.2.6p5-10.el6.centos.x86_64                                             2/2 
  Verifying  : ntpdate-4.2.6p5-10.el6.centos.x86_64                                         1/2 
  Verifying  : ntp-4.2.6p5-10.el6.centos.x86_64                                             2/2 

Installed:
  ntp.x86_64 0:4.2.6p5-10.el6.centos                                                            

Dependency Installed:
  ntpdate.x86_64 0:4.2.6p5-10.el6.centos                                                        

Complete!
[root@OpsDev2 ~]# date -R
Fri, 27 May 2016 03:31:41 +0200
[root@OpsDev2 ~]# /etc/localtime
-bash: /etc/localtime: Permission denied
[root@OpsDev2 ~]# date
Fri May 27 03:43:49 CEST 2016
[root@OpsDev2 ~]# localectl status
-bash: localectl: command not found
[root@OpsDev2 ~]# more /etc/sysconfig/clock 
ZONE="Europe/Berlin"
[root@OpsDev2 ~]# more /etc/localtime 
㯐ӠÑ lr!\c"LT#<E$,6%'&^L'C'䎨㥐)Ӗ*Ő+´쥩-ڐ.ː/t¼0d­1]א2r´3=»4R562x6

...skipping one line
\ ]´.̐`_Ӑa}ꏢ?·c]̐de=®µgg藐hꇹjܔk¨[lűm=n¦Sohp5qQ<rfs1tE㏐{λ|}®~y--More--(39%)
Most commands optionally preceded by integer argument k.  Defaults in brackets.
Star (*) indicates argument becomes new default.
-------------------------------------------------------------------------------
<space>                 Display next k lines of text [current screen size]
z                       Display next k lines of text [current screen size]*
<return>                Display next k lines of text [1]*
d or ctrl-D             Scroll k lines [current scroll size, initially 11]*
q or Q or <interrupt>   Exit from more
s                       Skip forward k lines of text [1]
f                       Skip forward k screenfuls of text [1]
b or ctrl-B             Skip backwards k screenfuls of text [1]
'                       Go to place where previous search started
=                       Display current line number
/<regular expression>   Search for kth occurrence of regular expression [1]
n                       Search for kth occurrence of last r.e [1]
!<cmd> or :!<cmd>       Execute <cmd> in a subshell
v                       Start up /usr/bin/vi at current line
ctrl-L                  Redraw screen
:n                      Go to kth next file [1]
:p                      Go to kth previous file [1]
:f                      Display current file name and line number
.                       Repeat previous command
-------------------------------------------------------------------------------
1
CET-1CEST,M3.5.0,M10.5.0/3
[root@OpsDev2 ~]# 
[root@OpsDev2 ~]# 
[root@OpsDev2 ~]# tzselect
Please identify a location so that time zone rules can be set correctly.
Please select a continent or ocean.
 1) Africa
 2) Americas
 3) Antarctica
 4) Arctic Ocean
 5) Asia
 6) Atlantic Ocean
 7) Australia
 8) Europe
 9) Indian Ocean
10) Pacific Ocean
11) none - I want to specify the time zone using the Posix TZ format.
#? ^C
[root@OpsDev2 ~]# vi /etc/sysconfig/clock
[root@OpsDev2 ~]# cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
cp: overwrite `/etc/localtime'? y
[root@OpsDev2 ~]# date
Fri May 27 10:01:58 CST 2016
[root@OpsDev2 ~]# . /etc/sysconfig/clock
[root@OpsDev2 ~]# date
Fri May 27 10:02:13 CST 2016
[root@OpsDev2 ~]# . /etc/localtime 
-bash: TZif2: command not found
[root@OpsDev2 ~]# date -R
Fri, 27 May 2016 10:08:04 +0800
[root@OpsDev2 ~]# yum remove ntp
Loaded plugins: fastestmirror
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package ntp.x86_64 0:4.2.6p5-10.el6.centos will be erased
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================
 Package         Arch               Version                             Repository         Size
================================================================================================
Removing:
 ntp             x86_64             4.2.6p5-10.el6.centos               @base             1.6 M

Transaction Summary
================================================================================================
Remove        1 Package(s)

Installed size: 1.6 M
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Erasing    : ntp-4.2.6p5-10.el6.centos.x86_64                                             1/1 
  Verifying  : ntp-4.2.6p5-10.el6.centos.x86_64                                             1/1 

Removed:
  ntp.x86_64 0:4.2.6p5-10.el6.centos                                                            

Complete!
[root@OpsDev2 ~]# exit
logout
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
id:1
[2016-05-27 10:13:34]导入模块报错：'NoneType' object has no attribute 'setAndReturnModule'
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
  File "jsonrpc.py", line 133, in validata_all
    if not func():
  File "jsonrpc.py", line 122, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module + "没有此函数" + self.funcname)
TypeError: cannot concatenate 'str' and 'NoneType' objects
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
id:1
[2016-05-27 10:31:47]导入模块报错：'NoneType' object has no attribute 'module_name'
Traceback (most recent call last):
  File "jsonrpc.py", line 333, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 39, in execute
    if self.validata_all():
  File "jsonrpc.py", line 133, in validata_all
    if not func():
  File "jsonrpc.py", line 122, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module + "没有此函数" + self.funcname)
TypeError: cannot concatenate 'str' and 'NoneType' objects
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
  File "jsonrpc.py", line 27
    print "模块名：%s，函数名：%s" % {self.module_name, self.funcname}
                                                               ^
SyntaxError: invalid syntax
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
[2016-05-27 10:37:34]导入模块报错：'NoneType' object has no attribute 'module_name'
Traceback (most recent call last):
  File "jsonrpc.py", line 334, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 40, in execute
    if self.validata_all():
  File "jsonrpc.py", line 134, in validata_all
    if not func():
  File "jsonrpc.py", line 123, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module + "没有此函数" + self.funcname)
TypeError: cannot concatenate 'str' and 'NoneType' objects
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
Traceback (most recent call last):
  File "jsonrpc.py", line 334, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 40, in execute
    if self.validata_all():
  File "jsonrpc.py", line 134, in validata_all
    if not func():
  File "jsonrpc.py", line 123, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module + "没有此函数" + self.funcname)
TypeError: cannot concatenate 'str' and 'module' objects
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
[2016-05-27 10:42:32]模块idc没有此函数getIdc
Traceback (most recent call last):
  File "jsonrpc.py", line 334, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 45, in execute
    self.response = self.response_preform.jsonError(self.jsondata["id"], errno, "jsonrpc调用失败，详见系统后台日志！")
NameError: global name 'errno' is not defined
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
[2016-05-27 10:44:39]模块idc没有此函数getIdc
测试execute方法{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "1", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
[2016-05-27 10:47:55]模块idc没有此函数getIdc
测试execute方法{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "1", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
测试execute方法{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "1", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
[2016-05-27 10:51:36]模块已导入过了。
None
测试execute方法{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "1", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
Traceback (most recent call last):
  File "jsonrpc.py", line 340, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 43, in execute
    self.response = self.response_preform.processresult(result)
  File "jsonrpc.py", line 170, in processresult
    self.result = json.dumps(format_sucess, ensure_ascii=False, indent=4)
  File "/usr/lib64/python2.6/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python2.6/json/encoder.py", line 367, in encode
    chunks = list(self.iterencode(o))
  File "/usr/lib64/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 317, in _iterencode
    for chunk in self._iterencode_default(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 323, in _iterencode_default
    newobj = self.default(o)
  File "/usr/lib64/python2.6/json/encoder.py", line 344, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function getIdc at 0x7faf97dca5f0> is not JSON serializable
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
<function getIdc at 0x7f8098a1a5f0>
Traceback (most recent call last):
  File "jsonrpc.py", line 341, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 44, in execute
    self.response = self.response_preform.processresult(result)
  File "jsonrpc.py", line 171, in processresult
    self.result = json.dumps(format_sucess, ensure_ascii=False, indent=4)
  File "/usr/lib64/python2.6/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python2.6/json/encoder.py", line 367, in encode
    chunks = list(self.iterencode(o))
  File "/usr/lib64/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 317, in _iterencode
    for chunk in self._iterencode_default(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 323, in _iterencode_default
    newobj = self.default(o)
  File "/usr/lib64/python2.6/json/encoder.py", line 344, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function getIdc at 0x7f8098a1a5f0> is not JSON serializable
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.py'>
验证通过：等待调用方法！
Traceback (most recent call last):
  File "jsonrpc.py", line 341, in <module>
    print "测试execute方法" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 42, in execute
    result = getattr(self.module, self.funcname)(self.jsondata.get("params"))
TypeError: getIdc() takes exactly 2 arguments (1 given)
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.py'>
验证通过：等待调用方法！
测试getIdc()方法
测试execute方法{
    "jsonrpc": "2.0", 
    "result": "测试getIdc()方法", 
    "id": 1
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
测试getIdc()方法
测试execute方法{
    "jsonrpc": "2.0", 
    "result": "测试getIdc()方法", 
    "id": 1
}
模块名：idc，函数名：getIdc_err
[2016-05-27 11:01:44]ID不正确，应该为1
[2016-05-27 11:01:44]ID不正确，应该为1
False
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
[2016-05-27 11:01:44]模块idc没有此函数getIdc_err
[2016-05-27 11:01:44]模块idc没有此函数getIdc_err
False
测试execute方法{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "2", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
发送正常数据测试返回执行结果：
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
测试getIdc()方法
测试execute方法：{
    "jsonrpc": "2.0", 
    "result": "测试getIdc()方法", 
    "id": 1
}
测试报错信息测试返回报错信息：
模块名：idc，函数名：getIdc_err
[2016-05-27 11:03:44]ID不正确，应该为1
[2016-05-27 11:03:44]ID不正确，应该为1
False
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
[2016-05-27 11:03:44]模块idc没有此函数getIdc_err
[2016-05-27 11:03:44]模块idc没有此函数getIdc_err
False
测试execute方法：{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "2", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
===============发送正常数据测试返回执行结果：===============
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
测试getIdc()方法
测试execute方法：{
    "jsonrpc": "2.0", 
    "result": "测试getIdc()方法", 
    "id": 1
}
===============测试报错信息测试返回报错信息：===============
模块名：idc，函数名：getIdc_err
[2016-05-27 11:19:06]ID不正确，应该为1
[2016-05-27 11:19:06]ID不正确，应该为1
False
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
[2016-05-27 11:19:06]模块idc没有此函数getIdc_err
[2016-05-27 11:19:06]模块idc没有此函数getIdc_err
False
测试execute方法：{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "2", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
===============发送正常数据测试返回执行结果：===============
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
测试getIdc()方法
测试execute方法：{
    "jsonrpc": "2.0", 
    "result": "测试getIdc()方法", 
    "id": 1
}
===============测试报错信息测试返回报错信息：===============
模块名：idc，函数名：getIdc_err
[2016-05-27 11:25:57]ID不正确，应该为1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
[2016-05-27 11:25:57]模块idc没有此函数getIdc_err
测试execute方法：{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "2", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
  File "jsonrpc.py", line 44
    print result
        ^
SyntaxError: invalid syntax
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
===============发送正常数据测试返回执行结果：===============
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
Traceback (most recent call last):
  File "jsonrpc.py", line 343, in <module>
    print "测试execute方法：" + jsonrpcTmp.execute()
  File "jsonrpc.py", line 43, in execute
    result = self.module.self.funcname(self.jsondata.get("params"))
AttributeError: 'module' object has no attribute 'self'
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
  File "jsonrpc.py", line 43
    result = self.module.(self.funcname)(self.jsondata.get("params"))
                         ^
SyntaxError: invalid syntax
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
  File "jsonrpc.py", line 43
    result = self.lazyImport.(self.funcname)(self.jsondata.get("params"))
                             ^
SyntaxError: invalid syntax
[vagrant@OpsDev2 Lesson01]$ python jsonrpc.py
===============发送正常数据测试返回执行结果：===============
模块名：idc，函数名：getIdc
id:1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
验证通过：等待调用方法！
测试getIdc()方法
测试execute方法：{
    "jsonrpc": "2.0", 
    "result": "测试getIdc()方法", 
    "id": 1
}
===============测试报错信息测试返回报错信息：===============
模块名：idc，函数名：getIdc_err
[2016-05-27 11:31:41]ID不正确，应该为1
<module 'modules.idc' from '/PythonHome/wwwroot/Lesson01/modules/idc.pyc'>
[2016-05-27 11:31:41]模块idc没有此函数getIdc_err
测试execute方法：{
    "error_code": 100, 
    "jsonrpc": "2.0", 
    "id": "2", 
    "errmsg": "jsonrpc调用失败，详见系统后台日志！"
}
[vagrant@OpsDev2 Lesson01]$ 

```